services:
  mysql:
    image: mysql:8.0
    container_name: notepad_app_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /home/Docker/db/notepad_app:/var/lib/mysql
    networks:
      - notepad_network

  app:
    build:
      context: .
    container_name: notepad_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql
    networks:
      - notepad_network

networks:
  notepad_network:
    driver: bridge

volumes:
  mysql_data:
