version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notepad_app_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notepad_app_123
      MYSQL_DATABASE: notepad_app_DB
      MYSQL_USER: notepad_app_user
      MYSQL_PASSWORD: notepad_app_123
    ports:
      - "3306:3306"
    volumes:
      - /home/Docker/db/notepad_app:/var/lib/mysql

volumes:
  mysql_data:
