### GET /
GET http://192.168.1.110:3000

### Register a new user POST /auth/register
POST http://192.168.1.110:3000/auth/register
Content-Type: application/json

{
    "username": "test",
    "password": "test123"
}

### Login a user POST /auth/login
POST http://192.168.1.110:3000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test123"
}